### ISSUE TITLE
Concept は Concept で見出しを設けたい

### ISSUE THREAD

**Issue by Azumabashi** [Nuink/TIG_WEB_2021#35]
ページをスクロールするといきなり「New Normal」が出てきて「なんだこれ？」になるので，そこはちゃんと Concept だと主張したほうがよさそう．
https://github.com/Nuink/TIG_WEB_2021/blob/main/src/components/sections/Concept.vue#L7 あたりに修正を加えればできそう．

**Comment by JunNishimura** [comment]
#49で一応解決しました
